"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['capture.py']
DATA_FILES = ['gui.py','imgurAppKey','plurkClient','PlurkOAuth.py','logo.png']
OPTIONS = {'argv_emulation': True,
		   'includes': ['requests','imgurpython','wx'],
		   'packages': ['requests','imgurpython','wx'],
		   'iconfile':'icon.icns'}

setup(
    app=APP,
    name='Capture',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app','wxpython','imgurpython']
)
